### ISSUE TITLE
Internal error when trying to join a global minigame

### ISSUE THREAD

**Issue by fox184** [AddstarMC/Minigames#193]
I was trying to create a global minigame, but when i launched it, internal error occurred. At first, i thought i've done something wrong with a minigame config. I created the "blank" global game, but i still could not join. What should i do now?

Console log:

> [14:19:00] [Server thread/INFO]: abc issued server command: /mg set pvp1 type global
> [14:19:02] [Server thread/INFO]: abc issued server command: /mg join pvp1
> [14:19:02] [Server thread/ERROR]: null
> org.bukkit.command.CommandException: Unhandled exception executing command 'mg' in plugin Minigames v1.12.0-SNAPSHOT-
> 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
> 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
> 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
> 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
> 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
> 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
> 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
> 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
> 	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
> 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
> 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
> 	at java.lang.Thread.run(Unknown Source) [?:?]
> Caused by: java.lang.NullPointerException
> 	at au.com.mineauz.minigames.PlayerData.joinMinigame(PlayerData.java:77) ~[?:?]
> 	at au.com.mineauz.minigames.commands.JoinCommand.onCommand(JoinCommand.java:64) ~[?:?]
> 	at au.com.mineauz.minigames.commands.CommandDispatcher.onCommand(CommandDispatcher.java:180) ~[?:?]
> 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
> 	... 15 more

Waiting for a response.

**Comment by Narimm** [comment]
I need to know which version your running ? 

I think this might have already been fixed in development

**Comment by fox184** [comment]
1.12.0-snapshot

**Comment by fox184** [comment]
I've installed the latest version 1.12.2-rc-258, but the error still exists.

**Comment by fox184** [comment]
However i've found out, that there is literally no difference between global and singleplayer games, so this issue can be closed.

**Comment by Narimm** [comment]
Thanks but with the latest version I will leave it open until I can determine that there he NPE is caught
